version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/payment_service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/item_service"
    schedule:
      interval: "weekly"