apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  timeout.reconciliation: 180s

  application.instanceLabelKey: argocd.argoproj.io/instance

  # Add Git repositories here if using private repos
  # repositories: |
  #   - url: https://github.com/your-org/your-repo