global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Product Service
  - job_name: "product-service"
    static_configs:
      - targets: ["product-service:8003"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  # Worker Service
  - job_name: "worker-service"
    static_configs:
      - targets: ["worker-service:8001"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
