apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.userService.name }}
spec:
  replicas: {{ .Values.userService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.userService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.userService.name }}
    spec:
      containers:
      - name: user-service
        image: {{ .Values.userService.image }}:{{ .Values.userService.tag }}
        ports:
        - containerPort: 8004
        resources:
          requests:
            memory: {{ .Values.userService.resources.requests.memory | default "60Mi" }}
            cpu: {{ .Values.userService.resources.requests.cpu | default "4m" }}
          limits:
            memory: {{ .Values.userService.resources.limits.memory | default "120Mi" }}
            cpu: {{ .Values.userService.resources.limits.cpu | default "10m" }}
        env:
          - name: SUPABASE_URL
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: SUPABASE_URL
          - name: SUPABASE_KEY
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: SUPABASE_KEY
          - name: KEYCLOAK_URL
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: KEYCLOAK_URL
          - name: KEYCLOAK_REALM
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: KEYCLOAK_REALM
          - name: KEYCLOAK_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: KEYCLOAK_ADMIN_USER
          - name: KEYCLOAK_ADMIN_PASS
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: KEYCLOAK_ADMIN_PASS
          - name: KEYCLOAK_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: KEYCLOAK_CLIENT_ID
          - name: KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: KEYCLOAK_CLIENT_SECRET
          - name: KEYCLOAK_CALLBACK_URI
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: KEYCLOAK_CALLBACK_URI
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 5
          periodSeconds: 5
