apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userService.name }}
spec:
  selector:
    app: {{ .Values.userService.name }}
  ports:
    - port: 8004
      targetPort: 8004
  type: ClusterIP
