apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.itemService.name }}
spec:
  replicas: {{ .Values.itemService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.itemService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.itemService.name }}
    spec:
      containers:
      - name: item-service
        image: {{ .Values.itemService.image }}:{{ .Values.itemService.tag }}
        ports:
        - containerPort: 8003
        resources:
          requests:
            memory: {{ .Values.itemService.resources.requests.memory | default "60Mi" }}
            cpu: {{ .Values.itemService.resources.requests.cpu | default "4m" }}
          limits:
            memory: {{ .Values.itemService.resources.limits.memory | default "120Mi" }}
            cpu: {{ .Values.itemService.resources.limits.cpu | default "10m" }}
        env:
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: item-service-secrets
              key: SUPABASE_URL
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: item-service-secrets
              key: SUPABASE_KEY
        - name: PRODUCTS_SERVICE_URL
          value: "http://products-service:8001"
        - name: KEYCLOAK_URL
          value: "{{ .Values.itemService.keycloakUrl | default \"http://keycloak:8080\" }}"
        - name: KEYCLOAK_REALM
          value: "{{ .Values.itemService.keycloakRealm | default \"BB\" }}"
        - name: INSECURE
          value: "{{ .Values.itemService.insecure | default \"false\" }}"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 5
