apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.itemService.name }}
spec:
  selector:
    app: {{ .Values.itemService.name }}
  ports:
    - port: 8003
      targetPort: 8003
  type: ClusterIP
