# Production Environment Configuration

app:
  name: payment-service-prod
  replicas: 3
  image: justingav/payment-service
  tag: latest
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 70
    targetMemory: 80
  resources:
    requests:
      memory: "125Mi"
      cpu: "50m"
    limits:
      memory: "250Mi"
      cpu: "200m"
  domain: payment-service-prod.ltu-m7011e-10.se
  email: jusgav-1@student.ltu.se
  environment: Production
  message: "Hello from Production Environment - Live Site"
  keycloakUrl: "http://keycloak:8080"
  keycloakRealm: "BB"
  insecure: "false"

# Item Service Configuration
itemService:
  name: item-service-prod
  replicas: 3
  image: justingav/item-service
  tag: latest
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 70
    targetMemory: 80
  resources:
    requests:
      memory: "125Mi"
      cpu: "50m"
    limits:
      memory: "250Mi"
      cpu: "200m"
  domain: item-service-prod.ltu-m7011e-10.se
  email: jusgav-1@student.ltu.se
  environment: Production
  message: "Hello from Item Service - Production!"
  keycloakUrl: "http://keycloak:8080"
  keycloakRealm: "BB"
  insecure: "false"

# User Service Configuration
userService:
  name: user-service-prod
  replicas: 3
  image: justingav/user-service
  tag: latest
  keycloakUrl: "http://keycloak:8080"
  keycloakRealm: "BB"
  insecure: "false"  # Strict SSL verification in production
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 70
    targetMemory: 80
  resources:
    requests:
      memory: "125Mi"
      cpu: "50m"
    limits:
      memory: "250Mi"
      cpu: "200m"
  domain: user-service-prod.ltu-m7011e-10.se
  email: jusgav-1@student.ltu.se
  environment: Production
  message: "Hello from User Service - Production!"

# Ingress configuration
ingress:
  enabled: true
  certIssuer: letsencrypt-prod
