# Production Environment Configuration

app:
  name: payment-service-prod
  replicas: 3
  image: justingav/payment-service
  tag: latest

# Production domain
domain: payment-service-prod.ltu-m7011e-10.se

# Email for Let's Encrypt certificates
email: jusgav-1@student.ltu.se

# Environment identifier
environment: Production

message: "Hello from Production Environment - Live Site"

# Ingress configuration
ingress:
  enabled: true
  certIssuer: letsencrypt-prod

# Item Service Configuration
itemService:
  name: item-service-prod
  replicas: 1
  image: justingav/item-service
  tag: latest
  
  # Item service domain  
  domain: item-service-prod.ltu-m7011e-10.se
  
  message: "Hello from Item Service - Production!"