app:
  name: payment-service
  replicas: 1
  image: justingav/payment-service
  tag: latest

domain: ltu-m7011e-10.se 
email: jusgav-1@student.ltu.se                

message: "Hello from Payment Service with SSL!"

ingress:
  enabled: true
