# Development Environment Configuration

app:
  name: payment-service-dev
  replicas: 1
  image: justingav/payment-service
  tag: latest
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 70
    targetMemory: 80
  resources:
    requests:
      memory: "125Mi"
      cpu: "50m"
    limits:
      memory: "250Mi"
      cpu: "200m"

# Development domain
domain: payment-service-dev.ronstad.se
# Email for Let's Encrypt certificates
email: jusgav-1@student.ltu.se

# Environment identifier
environment: Development

message: "Hello from Development Environment!"

# Ingress configuration
ingress:
  enabled: true
  certIssuer: letsencrypt-staging

# Item Service Configuration
itemService:
  name: item-service-dev
  replicas: 1
  image: justingav/item-service
  tag: latest
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 70
    targetMemory: 80
  resources:
    requests:
      memory: "125Mi"
      cpu: "50m"
    limits:
      memory: "250Mi"
      cpu: "200m"

  # Item service domain
  domain: item-service-dev.ronstad.se

  message: "Hello from Item Service - Development!"
